### ISSUE TITLE
train / valid / test split

### ISSUE THREAD

**Issue by expectopatronum** [renatopanda/TAFFC2018#1]
Hi,
I am looking into using your dataset for my research. In your paper you mention a 10-fold CV. It does not take care of the artist, right? Do you have a suggested train / validation / test split? Or are you aware of someone using the dataset with a fixed split? Just in case one existed I would like to use the same for comparability :)

Thanks for the great work and best regards
Verena

**Comment by renatopanda** [comment]
Hi Verena,

Thanks for your interest in this work.
Indeed, I used a simple 10-fold CV, which does not consider artists or albums, so songs from the same author can be spread across the various folds. Still, the random seed is set to 1 during execution to allow the replication of folds and results. We can try to export the resulting ten folds/groups of clips if you find that that would be useful.

We are currently working on the expansion of the dataset and also looking at that exact topic (provide a suggested TVT division, but I can't give you a clear estimation of the time left. If you find it easier, feel free to contact me at panda@dei.uc.pt 😄

**Comment by expectopatronum** [comment]
Hi Renato,

unfortunately I never received an email with your reply so I missed it 😅 I ended up creating my own split that takes the artist into account. Thanks a lot for the answer and I am really looking forward to an expansion of the dataset!

Best regards
Verena

**Comment by renatopanda** [comment]
Hello Verena,

No worries, that's normal since we all have a ton of tasks in hand. Still, great news that you solved your problem. My suggestion is indeed to share those splits (divisions) if you end up publishing your work, because it makes it easier for others to replicate things correctly. As for the expansion, it is still ongoing but once release I will try to get you notified :)

Cheers,
Renato
